enableGlobalCache: true

initScope: "es50678"
initFields:
  files:
    - "**/*.d.ts"
    - "**/*.js"
  license: UNLICENSED
  main: index.js

# authentication must be done at the global config ~/.yarnrc.yml
# ie:
# npmRegistries:
#  //npm.pkg.github.com:
#    npmAuthToken: TOKEN
npmScopes:
  es50678:
    npmRegistryServer: https://npm.pkg.github.com

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
